# Generated by Django 3.2.4 on 2021-06-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_messagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='file_field'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
